#pragma once

#include "introRL/linear.hpp"

namespace af
{
    class array;
}

namespace introRL::environments
{
    /// <summary>
    /// Generate rewards for a number of agents making one pull each from a number of
    /// slot machines.
    /// </summary>
    /// <param name="qStar">
    /// - A matrix of shape (agents, actions) holding the average rewards of the slot
    /// machines each agent can pull from.
    /// </param>
    /// <param name="linearActionIndices">
    /// - An array of one action index per agent, each one representing that agent's
    /// choice.
    /// </param>
    /// <returns>
    /// An array of rewards, one per agent, generated by sampling from a normal
    /// distribution centered on the chosen slot machine's average reward.
    /// </returns>
    const af::array bandit(const af::array& qStar, const af::array& linearActionIndices);
}